name: tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Prepare Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Prepare depdendency cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'

      - name: Run tests
        run: mvn --batch-mode --show-version --errors test --file pom.xml
